Update error management.

diff --git a/test/playbooks/ansible/aws/files/installAWS b/test/playbooks/ansible/aws/files/installAWS
--- a/test/playbooks/ansible/aws/files/installAWS
+++ b/test/playbooks/ansible/aws/files/installAWS
@@ -78,35 +78,9 @@ unzipAWS()
 
 error()
 {
-	case $1 in
-	20)
-		MESSAGE="Command $2 not available"
-		;;
-	25)
-		MESSAGE="Unable to create working directory"
-		;;
-	28)
-		MESSAGE="Unable to change directory to working directory"
-		;;
-	50)
-		MESSAGE="Attempt to download AWS CLI failed"
-		;;
-	60)
-		MESSAGE="Attempt to unzip AWS CLI failed"
-		;;
-	70)
-		MESSAGE="Attempt to install AWS CLI failed"
-		;;
-	90)
-		MESSAGE="Unable to remove working directory"
-		;;
-	*)
-		MESSAGE="No message"
-		;;
-	esac
-
-	echo "Error $1: $MESSAGE"
-	logger "Error $1: $MESSAGE"
+	echo "Error $1:"
+	logger "Error $1"
+	exit $1
 }
 
 initialise()
diff --git a/test/playbooks/ansible/kubernetes/files/installKubernetes b/test/playbooks/ansible/kubernetes/files/installKubernetes
--- a/test/playbooks/ansible/kubernetes/files/installKubernetes
+++ b/test/playbooks/ansible/kubernetes/files/installKubernetes
@@ -103,47 +103,42 @@ installKubectl()
 installMiniKube()
 {
 	cp minikube-linux-amd64 /usr/local/bin/minikube
+	case $? in
+	0)
+		echo "Success!"
+		;;
+	*)
+		error 70
+		;;
+	esac
 
 	chmod 755 /usr/local/bin/minikube
+	case $? in
+	0)
+		echo "Success!"
+		;;
+	*)
+		error 73
+		;;
+	esac
 
 	minikube version
+	case $? in
+	0)
+		echo "Success!"
+		;;
+	*)
+		error 76
+		;;
+	esac
 }
 
 
 error()
 {
-	case $1 in
-	20)
-		MESSAGE="Command $2 not available"
-		;;
-	25)
-		MESSAGE="Unable to create working directory"
-		;;
-	28)
-		MESSAGE="Unable to change directory to working directory"
-		;;
-	50)
-		MESSAGE="Attempt to download kubectl failed"
-		;;
-	55)
-		MESSAGE="Attempt to install kubectl failed"
-		;;
-	60)
-		MESSAGE="Attempt to download minikube failed"
-		;;
-	65)
-		MESSAGE="Attempt to set permissions on kubectl failed"
-		;;
-	90)
-		MESSAGE="Unable to remove working directory"
-		;;
-	*)
-		MESSAGE="Unknown error"
-		;;
-	esac
-
-	echo $MESSAGE
-	logger $MESSAGE
+    echo "Error $1:"
+    logger "Error $1"
+    exit $1
 }
 
 initialise()
@@ -159,7 +154,7 @@ initialise()
 			echo "Command $I available"
 			;;
 		*)
-			error 20 $I
+			error 20
 			;;
 		esac
 	done
@@ -188,6 +183,14 @@ initialise()
 startMinikube()
 {
 	minikube start
+	case $? in
+	0)
+		echo "Success!"
+		;;
+	*)
+		error 80
+		;;
+	esac
 }
 
 #
diff --git a/test/playbooks/ansible/nvm/files/installNVM b/test/playbooks/ansible/nvm/files/installNVM
--- a/test/playbooks/ansible/nvm/files/installNVM
+++ b/test/playbooks/ansible/nvm/files/installNVM
@@ -1,6 +1,26 @@
 #!/bin/bash
 
-curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
+#
+# Functions
+#
+
+downloadScript
+{
+	curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
+}
+
+error()
+{
+    echo "Error $1:"
+    logger "Error $1"
+    exit $1
+}
+
+#
+# Main
+#
+
+downloadScript
 
 if [ -d "$HOME/.nvm" ]; then
   # export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
